In [39]:
# read csvs

import pandas as pd
import numpy as np
import itertools

In [40]:
cuartel1 = pd.read_csv('data_sensores.csv')
cuartel2 = pd.read_csv('p4s2Final.csv')

In [41]:
# Hacer que todos los datos de todas las columnas de ambos dataframes, tengan como maximo 2 decimales 

cuartel1 = cuartel1.round(2)   

# Juntar columnas de Fecha y Hora en una sola, para cuartel2, en una nueva columna FechaHora

cuartel2['FechaHora'] = cuartel2['Fecha'] + ' ' + cuartel2['Hora']

# Elimino las columnas Fecha y Hora

cuartel2 = cuartel2.drop(columns=['Fecha', 'Hora'])

# Agregar a cuartel2 las columnas de Nitrogeno, Fosforo, Potasio, pH que estan en cuartel1

cuartel2['Nitrogeno'] = cuartel1['Nitrogeno']
cuartel2['Fosforo'] = cuartel1['Fosforo']
cuartel2['Potasio'] = cuartel1['Potasio']
cuartel2['pH'] = cuartel1['pH']

# Función para rellenar valores vacíos de forma cíclica
def fill_cyclic(df, columns):
    for col in columns:
        values = df[col].dropna().tolist()  # Obtiene los valores no nulos como lista
        if values:  # Asegurarse de que haya valores para ciclar
            cycle_values = itertools.cycle(values)  # Crea un ciclo infinito con los valores
            df[col] = df[col].apply(lambda x: next(cycle_values) if pd.isna(x) else x)  # Rellena valores NaN cíclicamente
    return df

# Definir las columnas a rellenar
columns_to_fill = ['Fosforo', 'Nitrogeno', 'Potasio', 'pH']

# Aplicar la función al DataFrame
cuartel2 = fill_cyclic(cuartel2, columns_to_fill)


# Quiero reordenar las columnas de cuartel2 para que queden en el siguiente orden:
# FechaHora,Nitrogeno,Fosforo,Potasio,Conductividad_Electrica,pH,Humedad,Temperatura y luego las demas columnas

cuartel2 = cuartel2[['FechaHora','Nitrogeno','Fosforo','Potasio','Conductividad_Electrica','pH','Humedad','Temperatura'] + [col for col in cuartel2.columns if col not in ['FechaHora','Nitrogeno','Fosforo','Potasio','Conductividad_Electrica','pH','Humedad','Temperatura']]]

In [42]:
cuartel2.tail(5)

,FechaHora,Nitrogeno,Fosforo,Potasio,Conductividad_Electrica,pH,Humedad,Temperatura,m8 (10 cm) [mm],m8 (20 cm) [mm],m8 (60 cm) [mm],m8 (80 cm) [mm],m8 (100 cm) [mm],tz (T Amb superficie) [C]
8715,2024-10-03 00:21:56,<function fill_cyclic.<locals>.<lambda> at 0x7...,<function fill_cyclic.<locals>.<lambda> at 0x7...,<function fill_cyclic.<locals>.<lambda> at 0x7...,3.49,<function fill_cyclic.<locals>.<lambda> at 0x7...,62.85,13.50,57.52,63.23,61.37,66.28,40.72,13.93
8716,2024-10-03 03:12:04,<function fill_cyclic.<locals>.<lambda> at 0x7...,<function fill_cyclic.<locals>.<lambda> at 0x7...,<function fill_cyclic.<locals>.<lambda> at 0x7...,3.50,<function fill_cyclic.<locals>.<lambda> at 0x7...,62.63,13.50,57.18,62.98,61.17,66.33,40.75,13.18
8717,2024-10-03 05:22:11,<function fill_cyclic.<locals>.<lambda> at 0x7...,<function fill_cyclic.<locals>.<lambda> at 0x7...,<function fill_cyclic.<locals>.<lambda> at 0x7...,3.51,<function fill_cyclic.<locals>.<lambda> at 0x7...,62.51,13.50,56.96,62.81,61.05,66.36,40.77,12.62
8718,2024-10-03 08:22:20,<function fill_cyclic.<locals>.<lambda> at 0x7...,<function fill_cyclic.<locals>.<lambda> at 0x7...,<function fill_cyclic.<locals>.<lambda> at 0x7...,3.65,<function fill_cyclic.<locals>.<lambda> at 0x7...,62.36,13.50,56.70,62.61,60.92,66.35,40.79,12.12
8719,2024-10-03 11:12:29,<function fill_cyclic.<locals>.<lambda> at 0x7...,<function fill_cyclic.<locals>.<lambda> at 0x7...,<function fill_cyclic.<locals>.<lambda> at 0x7...,3.57,<function fill_cyclic.<locals>.<lambda> at 0x7...,61.90,13.56,56.08,61.99,60.57,66.19,40.78,12.75

In [43]:
cuartel1.tail(5)

,FechaHora,Nitrogeno,Fosforo,Potasio,Conductividad_Electrica,pH,Humedad,Temperatura
1090,2023-12-30 12:00:00,118.48,44.43,150.16,1.02,6.44,77.63,19.59
1091,2023-12-30 21:00:00,121.88,43.73,148.62,0.82,6.53,73.46,20.31
1092,2023-12-31 03:00:00,119.65,42.64,151.12,1.01,6.46,56.16,25.01
1093,2023-12-31 12:00:00,118.70,43.92,150.40,1.04,6.62,81.29,26.31
1094,2023-12-31 21:00:00,118.45,44.37,148.76,0.95,6.32,67.97,23.53

In [44]:
# guardar ambos dataframes como cuartel1.csv y cuartel2.csv

cuartel1.to_csv('cuartel1.csv', index=False)
cuartel2.to_csv('cuartel2.csv', index=False)