In [1]:
# read csvs

import pandas as pd
import numpy as np
import itertools

In [23]:
cuartel1 = pd.read_csv('p0s0.csv')
cuartel2 = pd.read_csv('p6s4.csv')

In [24]:
cuartel2.head()

,Fecha,Hora,Conductividad_Electrica,m8 (10 cm) [mm],m8 (20 cm) [mm],Humedad,m8 (60 cm) [mm],m8 (80 cm) [mm],m8 (100 cm) [mm],Temperatura,tz (T Amb superficie) [C],v7 (Voltaje) [V]
0,2020-01-04,00:09:29,6.33,65.87,70.16,68.78,67.42,42.74,43.65,16.43,16.18,NaN
1,2020-01-04,05:59:46,6.30,65.51,69.93,68.65,67.43,42.76,43.74,16.5,15.25,NaN
2,2020-01-04,12:00:04,6.61,65.44,69.76,68.54,67.44,42.81,43.82,16.5,16.62,NaN
3,2020-01-04,17:50:22,6.58,65.58,69.87,68.46,67.42,42.83,43.86,16.43,19.81,NaN
4,2020-01-04,23:50:40,6.33,64.87,69.82,68.47,67.4,42.85,43.89,16.5,17.0,NaN

In [25]:
# Hacer que todos los datos de todas las columnas de ambos dataframes, tengan como maximo 2 decimales 

#cuartel1 = cuartel1.round(2)   

# Juntar columnas de Fecha y Hora en una sola, para cuartel2, en una nueva columna FechaHora

cuartel2['FechaHora'] = cuartel2['Fecha'] + ' ' + cuartel2['Hora']

# Elimino las columnas Fecha y Hora

cuartel2 = cuartel2.drop(columns=['Fecha', 'Hora'])

# Agregar a cuartel2 las columnas de Nitrogeno, Fosforo, Potasio, pH que estan en cuartel1

cuartel2['Nitrogeno'] = cuartel1['Nitrogeno']
cuartel2['Fosforo'] = cuartel1['Fosforo']
cuartel2['Potasio'] = cuartel1['Potasio']
cuartel2['pH'] = cuartel1['pH']

# Función para rellenar valores vacíos de forma cíclica
def fill_cyclic(df, columns):
    for col in columns:
        values = df[col].dropna().tolist()  # Obtiene los valores no nulos como lista
        if values:  # Asegurarse de que haya valores para ciclar
            cycle_values = itertools.cycle(values)  # Crea un ciclo infinito con los valores
            df[col] = df[col].apply(lambda x: next(cycle_values) if pd.isna(x) else x)  # Rellena valores NaN cíclicamente
    return df

# Definir las columnas a rellenar
columns_to_fill = ['Fosforo', 'Nitrogeno', 'Potasio', 'pH']

# Aplicar la función al DataFrame
cuartel2 = fill_cyclic(cuartel2, columns_to_fill)


# Quiero reordenar las columnas de cuartel2 para que queden en el siguiente orden:
# FechaHora,Nitrogeno,Fosforo,Potasio,Conductividad_Electrica,pH,Humedad,Temperatura y luego las demas columnas

cuartel2 = cuartel2[['FechaHora','Nitrogeno','Fosforo','Potasio','Conductividad_Electrica','pH','Humedad','Temperatura'] + [col for col in cuartel2.columns if col not in ['FechaHora','Nitrogeno','Fosforo','Potasio','Conductividad_Electrica','pH','Humedad','Temperatura']]]

In [26]:
cuartel2.tail(5)

,FechaHora,Nitrogeno,Fosforo,Potasio,Conductividad_Electrica,pH,Humedad,Temperatura,m8 (10 cm) [mm],m8 (20 cm) [mm],m8 (60 cm) [mm],m8 (80 cm) [mm],m8 (100 cm) [mm],tz (T Amb superficie) [C],v7 (Voltaje) [V]
7874,2024-10-03 00:03:32,126.35,65.52,192.71,6.22,6.91,56.45,13.56,59.55,60.56,60.09,49.74,29.76,10.21,NaN
7875,2024-10-03 05:43:48,124.80,63.02,193.49,6.17,6.77,55.64,13.62,57.99,59.6,59.42,49.98,29.77,10,NaN
7876,2024-10-03 11:44:04,123.83,61.96,191.62,6.51,6.89,--,--,--,--,--,--,--,--,NaN
7877,2024-10-03 18:04:21,124.90,63.91,191.88,6.52,6.86,--,--,--,--,--,--,--,--,NaN
7878,2024-10-03 23:54:36,124.43,60.46,190.18,6.22,6.82,--,--,--,--,--,--,--,--,NaN

In [27]:
cuartel1.tail(5)

,FechaHora,Nitrogeno,Fosforo,Potasio,Conductividad_Electrica,pH,Humedad,Temperatura
1090,2023-12-30 12:00:00,118.48,44.43,150.16,1.02,6.44,77.63,19.59
1091,2023-12-30 21:00:00,121.88,43.73,148.62,0.82,6.53,73.46,20.31
1092,2023-12-31 03:00:00,119.65,42.64,151.12,1.01,6.46,56.16,25.01
1093,2023-12-31 12:00:00,118.70,43.92,150.40,1.04,6.62,81.29,26.31
1094,2023-12-31 21:00:00,118.45,44.37,148.76,0.95,6.32,67.97,23.53

In [28]:
# guardar ambos dataframes como cuartel1.csv y cuartel2.csv

#cuartel1.to_csv('cuartel1.csv', index=False)
cuartel2.to_csv('p6s4.csv', index=False)